import { cart } from "./modules/cart";
import { getGoods } from "./modules/getGoods";
import { search } from "./modules/search";
import { slider } from "./modules/slider";
import { smoothScroll } from "./modules/smoothScroll";
getGoods();
cart();
search();
slider();
smoothScroll();
